### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by goanpeca** [kephale/napari-workshop-browser#2]
Hi @kephale, the dependencies need to be update to include:

    - appdirs
    - requests

Cheers!

**Comment by yunhal** [comment]
In my case, I had to install the following module separately in order to make it work: 
```
- platformdirs 
```

Side note to share: I am not sure what caused this problem but my python did not recognize 'platformdirs' module when I installed via PIP.  It works only after I did "conda install -c conda-forge platformdirs".

**Comment by kephale** [comment]
Thank you @goanpeca !

@yunhal is that still required if you add `appdirs` like @goanpeca suggested? I don't believe that `platformdirs` should be required.

**Comment by yunhal** [comment]
My dependency problem turned out to be unrelated to this plugin - it was coming from my jupyter environment. I used my existing conda environment to try this, and I got a few issues to be resolved to make it work.  It would be best to use this plugin in a new environment in order to above any potential installation issues.
